import { IconReference } from '../model/icon-references';

export const ICON_REFERENCES: IconReference[] = [
  {
    id: 1,
    title: 'Device Activating SVG Vector',
    collection: 'Brightlayer UI Icons',
    license: 'MIT License',
    author: 'etn-ccis',
    url: 'https://www.svgrepo.com/svg/503276/device-activating',
    iconPath: 'device-icon.svg',
    altText: 'Black device with black signal on top.',
  },
  {
    id: 2,
    title: 'Frozen House Ice SVG Vector',
    collection: 'Winter Duotone Glyph Vectors',
    license: 'CC Attribution License',
    author: 'Ruslan Mullakaev',
    url: 'https://www.svgrepo.com/svg/420426/frozen-house-ice',
    iconPath: 'frozen-house-icon.svg',
    altText: 'Black house with blue ice on top.',
  },
  {
    id: 3,
    title: 'Home 2 SVG Vector',
    collection: 'Iconfy Duotone Line Icons',
    license: 'CC Attribution License',
    author: 'Dimas nanda',
    url: 'https://www.svgrepo.com/svg/485521/home-2',
    iconPath: 'home-icon-main.svg',
    altText: 'House with blue roof. The walls and base are black.',
  },
  {
    id: 4,
    title: 'Home Alt 3 SVG Vector',
    collection: 'Variety Duotone Filled Icons',
    license: 'PD License',
    author: 'Mary Akveo',
    url: 'https://www.svgrepo.com/svg/465259/home-alt-3',
    iconPath: 'home-icon-summary.svg',
    altText: 'Home icon with all black color.',
  },
  {
    id: 5,
    title: 'Location Pin SVG Vector',
    collection: 'Orchid Line Interface Icons',
    license: 'MIT License',
    author: 'Orchid',
    url: 'https://www.svgrepo.com/svg/509148/location-pin',
    iconPath: 'location-icon.svg',
    altText: 'Black location icon with black circle in the middle.',
  },
  {
    id: 6,
    title: 'Thermometer Temperature SVG',
    collection: 'Winter 4',
    license: 'CC0 License',
    author: 'SVG Repo',
    url: 'https://www.svgrepo.com/svg/222623/thermometer-temperature',
    iconPath: 'temperature-icon.svg',
    altText: 'Light blue and gray thermometer icon with yellow shapes around the outside.',
  },
  {
    id: 7,
    title: 'Error SVG Vector',
    collection: 'Iconpark Duotone Icons',
    license: 'Apache License',
    author: 'bytedance',
    url: 'https://www.svgrepo.com/svg/387486/error',
    iconPath: 'captive-error-icon.svg',
    altText: 'Blue X Icon with bold black outline.',
  },
  {
    id: 8,
    title: 'Triangle Exclamation SVG Vector',
    collection: 'Dazzle Line Icons',
    license: 'CC Attribution License',
    author: 'Dazzle UI',
    url: 'https://www.svgrepo.com/svg/533742/triangle-exclamation',
    notes: 'Outline color changed from #000000 to #039ae5.',
    iconPath: 'data-unavailable-error-icon.svg',
    altText: 'Blue triangle with blue exclamation inside.',
  },
  {
    id: 9,
    title: 'Time SVG Vector',
    collection: 'Iconpark Duotone Icons',
    license: 'Apache License',
    author: 'bytedance',
    url: 'https://www.svgrepo.com/svg/388773/time',
    iconPath: 'session-timeout-error-icon.svg',
    altText: 'Blue clock with white hands and bold black outline.',
  },
  {
    id: 10,
    title: 'Circle SVG Vector',
    collection: 'Chunk 16px Thick Interface Icons',
    license: 'PD License',
    author: 'Noah Jacobus',
    url: 'https://www.svgrepo.com/svg/535262/circle',
    iconPath: 'healthy-location-temperature-icon.svg',
    altText: 'Green circle alert icon.',
  },
  {
    id: 11,
    title: 'Circle SVG Vector',
    collection: 'Chunk 16px Thick Interface Icons',
    license: 'PD License',
    author: 'Noah Jacobus',
    url: 'https://www.svgrepo.com/svg/535262/circle',
    iconPath: 'alert-location-temperature-icon.svg',
    altText: 'Red circle alert icon.',
  },
  {
    id: 12,
    title: 'Triangle Exclamation SVG Vector',
    collection: 'Dazzle Line Icons',
    license: 'CC Attribution License',
    author: 'Dazzle UI',
    url: 'https://www.svgrepo.com/svg/533742/triangle-exclamation',
    iconPath: 'no-data-location-temperature-icon.svg',
    altText: 'White triangle with black border and black exclamation mark alert icon.',
  },
  {
    id: 14,
    title: 'Thermometer SVG Vector',
    collection: 'Weather 28',
    license: 'CC0 License',
    author: 'SVG Repo',
    url: 'https://www.svgrepo.com/svg/225305/thermometer',
    iconPath: 'thermometer-temperate-icon.svg',
    altText: 'Orange thermometer icon.',
  },
  {
    id: 15,
    title: 'Thermometer Temperature SVG',
    collection: 'Weather 25',
    license: 'CC0 License',
    author: 'SVG Repo',
    url: 'https://www.svgrepo.com/svg/223556/thermometer-temperature',
    iconPath: 'thermometer-cold-icon.svg',
    altText: 'Blue thermometer icon.',
  },
  {
    id: 16,
    title: 'Thermometer SVG Vector',
    collection: 'Weather 27',
    license: 'CC0 License',
    author: 'SVG Repo',
    url: 'https://www.svgrepo.com/svg/223625/thermometer',
    iconPath: 'thermometer-alert-icon.svg',
    altText: 'Red thermometer icon (alert icon).',
  },
  {
    id: 17,
    title: 'Thermometer SVG Vector',
    collection: 'Weather 26',
    license: 'CC0 License',
    author: 'SVG Repo',
    url: 'https://www.svgrepo.com/svg/223593/thermometer',
    iconPath: 'thermometer-success-icon.svg',
    altText: 'Green thermometer icon (success icon).',
  },
  {
    id: 18,
    title: 'Thermometer SVG Vector',
    collection: 'Weather 28',
    license: 'CC0 License',
    author: 'SVG Repo',
    url: 'https://www.svgrepo.com/svg/225309/thermometer',
    iconPath: 'thermometer-warning-icon.svg',
    altText: 'Yellow thermometer icon (warning icon).',
  },
  {
    id: 19,
    title: 'Thermometer Temperature SVG',
    collection: 'Weather 25',
    license: 'CC0 License',
    author: 'SVG Repo',
    url: 'https://www.svgrepo.com/svg/223563/thermometer-temperature',
    iconPath: 'thermometer-info-icon.svg',
    altText: 'Blue thermometer icon (info icon).',
  },
];
