import { IconReference } from '../model/icon-references';

export const ICON_REFERENCES: IconReference[] = [
  {
    title: 'Device Activating SVG Vector',
    collection: 'Brightlayer UI Icons',
    license: 'MIT License',
    author: 'etn-ccis',
    url: 'https://www.svgrepo.com/svg/503276/device-activating',
    iconPath: 'device-icon.svg',
    altText: 'Black device with black signal on top.',
  },
  {
    title: 'Frozen House Ice SVG Vector',
    collection: 'Winter Duotone Glyph Vectors',
    license: 'CC Attribution License',
    author: 'Ruslan Mullakaev',
    url: 'https://www.svgrepo.com/svg/420426/frozen-house-ice',
    iconPath: 'frozen-house-icon.svg',
    altText: 'Black house with blue ice on top.',
  },
  {
    title: 'Home 2 SVG Vector',
    collection: 'Iconfy Duotone Line Icons',
    license: 'CC Attribution License',
    author: 'Dimas nanda',
    url: 'https://www.svgrepo.com/svg/485521/home-2',
    iconPath: 'home-icon-main.svg',
    altText: 'House with blue roof. The walls and base are black.',
  },
  {
    title: 'Home Alt 3 SVG Vector',
    collection: 'Variety Duotone Filled Icons',
    license: 'PD License',
    author: 'Mary Akveo',
    url: 'https://www.svgrepo.com/svg/465259/home-alt-3',
    iconPath: 'home-icon-summary.svg',
    altText: 'Home icon with all black color.',
  },
  {
    title: 'Location Pin SVG Vector',
    collection: 'Orchid Line Interface Icons',
    license: 'MIT License',
    author: 'Orchid',
    url: 'https://www.svgrepo.com/svg/509148/location-pin',
    iconPath: 'location-icon.svg',
    altText: 'Black location icon with black circle in the middle.',
  },
  {
    title: 'Thermometer Temperature SVG',
    collection: 'Winter 4',
    license: 'CC0 License',
    author: 'SVG Repo',
    url: 'https://www.svgrepo.com/svg/222623/thermometer-temperature',
    iconPath: 'temperature-icon.svg',
    altText: 'Light blue and gray thermometer icon with yellow shapes around the outside.',
  },
  {
    title: 'Error SVG Vector',
    collection: 'Iconpark Duotone Icons',
    license: 'Apache License',
    author: 'bytedance',
    url: 'https://www.svgrepo.com/svg/387486/error',
    iconPath: 'captive-error-icon.svg',
    altText: 'Blue X Icon with bold black outline.',
  },
  {
    title: 'Triangle Exclamation SVG Vector',
    collection: 'Dazzle Line Icons',
    license: 'CC Attribution License',
    author: 'Dazzle UI',
    url: 'https://www.svgrepo.com/svg/533742/triangle-exclamation',
    notes: 'Outline color changed from #000000 to #039ae5.',
    iconPath: 'data-unavailable-error-icon.svg',
    altText: 'Blue triangle with blue exclamation inside.',
  },
  {
    title: 'Time SVG Vector',
    collection: 'Iconpark Duotone Icons',
    license: 'Apache License',
    author: 'bytedance',
    url: 'https://www.svgrepo.com/svg/388773/time',
    iconPath: 'session-timeout-error-icon.svg',
    altText: 'Blue clock with white hands and bold black outline.',
  },
  {
    title: 'Circle SVG Vector',
    collection: 'Chunk 16px Thick Interface Icons',
    license: 'PD License',
    author: 'Noah Jacobus',
    url: 'https://www.svgrepo.com/svg/535262/circle',
    iconPath: 'healthy-location-temperature-icon.svg',
    altText: 'Green circle alert icon.',
  },
  {
    title: 'Circle SVG Vector',
    collection: 'Chunk 16px Thick Interface Icons',
    license: 'PD License',
    author: 'Noah Jacobus',
    url: 'https://www.svgrepo.com/svg/535262/circle',
    iconPath: 'alert-location-temperature-icon.svg',
    altText: 'Red circle alert icon.',
  },
];
